//
// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ     This file is generated by The Interactive Disassembler (IDA)        บ
// บ     Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>           บ
// บ                      Licensed to: Freeware version                      บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
//
//
//      This file contains the user-defined type definitions.
//      To use it press F2 in IDA and enter the name of this file.
//

#define UNLOADED_FILE   1
#include <idc.idc>

static main(void) {
        Enums();                // enumerations
        Structures();           // structure types
	LowVoids(0x10000);
	HighVoids(0x7FFE6000);
}

static Enums_0(id) {

	id = AddEnum(-1,"ADDRESS_MODE",0x1100000);
	AddConstEx(id,"AddrMode1616",	0X0,	-1);
	AddConstEx(id,"AddrMode1632",	0X1,	-1);
	AddConstEx(id,"AddrModeReal",	0X2,	-1);
	AddConstEx(id,"AddrModeFlat",	0X3,	-1);
	return id;
}

//------------------------------------------------------------------------
// Information about enum types

static Enums(void) {
        auto id;
	id = Enums_0(id);
}

static Structures_0(id) {

	id = AddStrucEx(-1,"tagMSG",0);
	id = AddStrucEx(-1,"tagPOINT",0);
	id = AddStrucEx(-1,"POINTL",0);
	id = AddStrucEx(-1,"_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4::$5ACE225D4D14CE0550A9F5A217E306C5",0);
	id = AddStrucEx(-1,"_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4",1);
	id = AddStrucEx(-1,"_devicemodeA",0);
	id = AddStrucEx(-1,"WSAData",0);
	id = AddStrucEx(-1,"FILETIME",0);
	id = AddStrucEx(-1,"_WIN32_FIND_DATAA",0);
	id = AddStrucEx(-1,"POINT",0);
	id = AddStrucEx(-1,"RECT",0);
	id = AddStrucEx(-1,"FILE",0);
	id = AddStrucEx(-1,"tm",0);
	id = AddStrucEx(-1,"sockaddr",0);
	id = AddStrucEx(-1,"timeval",0);
	id = AddStrucEx(-1,"fd_set",0);
	id = AddStrucEx(-1,"WNDCLASSEXA",0);
	id = AddStrucEx(-1,"tagWNDCLASSEXA",0);
	id = AddStrucEx(-1,"RGBQUAD",0);
	id = AddStrucEx(-1,"BITMAPINFOHEADER",0);
	id = AddStrucEx(-1,"BITMAPINFO",0);
	id = AddStrucEx(-1,"tagINITCOMMONCONTROLSEX",0);
	id = AddStrucEx(-1,"_OSVERSIONINFOA",0);
	id = AddStrucEx(-1,"_SYSTEMTIME",0);
	id = AddStrucEx(-1,"_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2::$AA04DEB0C6383F89F13D312A174572A9",0);
	id = AddStrucEx(-1,"_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2",1);
	id = AddStrucEx(-1,"_SYSTEM_INFO",0);
	id = AddStrucEx(-1,"_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E",0);
	id = AddStrucEx(-1,"LARGE_INTEGER",1);
	id = AddStrucEx(-1,"_SECURITY_ATTRIBUTES",0);
	id = AddStrucEx(-1,"SYSTEMTIME",0);
	id = AddStrucEx(-1,"_TIME_ZONE_INFORMATION",0);
	id = AddStrucEx(-1,"_STARTUPINFOA",0);
	id = AddStrucEx(-1,"_cpinfo",0);
	id = AddStrucEx(-1,"_FILETIME",0);
	id = AddStrucEx(-1,"KDHELP",0);
	id = AddStrucEx(-1,"ADDRESS",0);
	id = AddStrucEx(-1,"_tagSTACKFRAME",0);
	id = AddStrucEx(-1,"_MEMORY_BASIC_INFORMATION",0);
	id = AddStrucEx(-1,"LOGFONTA",0);
	id = AddStrucEx(-1,"tagSIZE",0);
	id = AddStrucEx(-1,"tagRECT",0);
	id = AddStrucEx(-1,"ICONINFO",0);
	id = AddStrucEx(-1,"WNDCLASSA",0);
	id = AddStrucEx(-1,"IID",0);
	id = AddStrucEx(-1,"CLSID",0);
	id = AddStrucEx(-1,"tagWNDCLASSA",0);
	id = AddStrucEx(-1,"SAFEARRAYBOUND",0);
	id = AddStrucEx(-1,"tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301::$674876891A86A76F12C10005982BCA56",0);
	id = AddStrucEx(-1,"tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301",1);
	id = AddStrucEx(-1,"tagDEC::$64EC678C49E7BE49873AFBFB7A849D34::$7F8459940C2B08BD5D82B0F27239141B",0);
	id = AddStrucEx(-1,"tagDEC::$64EC678C49E7BE49873AFBFB7A849D34",1);
	id = AddStrucEx(-1,"DECIMAL",0);
	id = AddStrucEx(-1,"tagVARIANT::$::$::$0BEA0A4089964397D04279FA271AA80F::$0FDBD249F1AECD6A49409B6B82281578",0);
	id = AddStrucEx(-1,"tagCY::$4ADA6AE34E722E24764E0C4FBCDA3E73",0);
	id = AddStrucEx(-1,"CY",1);
	id = AddStrucEx(-1,"tagVARIANT::$::$96DBE208241BA05363E12043D50C05A8::$0BEA0A4089964397D04279FA271AA80F",1);
	id = AddStrucEx(-1,"tagVARIANT::$33EB7139E59CDB065A159F13B94F651E::$96DBE208241BA05363E12043D50C05A8",0);
	id = AddStrucEx(-1,"tagVARIANT::$33EB7139E59CDB065A159F13B94F651E",1);
	id = AddStrucEx(-1,"VARIANTARG",0);
	id = AddStrucEx(-1,"_RTL_CRITICAL_SECTION",0);
	id = AddStrucEx(-1,"CPPEH_RECORD",0);
	
	id = GetStrucIdByName("POINT");
	AddStrucMember(id,"x",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"y",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("tagMSG");
	AddStrucMember(id,"hwnd",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"message",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"wParam",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"lParam",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"time",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"pt",	0X14,	0x60000400,	GetStrucIdByName("POINT"),	8);
	
	id = GetStrucIdByName("tagPOINT");
	AddStrucMember(id,"x",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"y",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("POINTL");
	AddStrucMember(id,"x",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"y",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4::$5ACE225D4D14CE0550A9F5A217E306C5");
	AddStrucMember(id,"dmOrientation",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmPaperSize",	0X2,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmPaperLength",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmPaperWidth",	0X6,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4::$5ACE225D4D14CE0550A9F5A217E306C5"),	8);
	AddStrucMember(id,"dmPosition",	0X0,	0x60000400,	GetStrucIdByName("POINTL"),	8);
	
	id = GetStrucIdByName("_devicemodeA");
	AddStrucMember(id,"dmDeviceName",	0X0,	0x000400,	-1,	32);
	AddStrucMember(id,"dmSpecVersion",	0X20,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmDriverVersion",	0X22,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmSize",	0X24,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmDriverExtra",	0X26,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmFields",	0X28,	0x20000400,	-1,	4);
	AddStrucMember(id,"anonymous_0",	0X2C,	0x60000400,	GetStrucIdByName("_devicemodeA::$1DE029518E5B112A14BB6E76DECCA4C4"),	8);
	AddStrucMember(id,"dmScale",	0X34,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmCopies",	0X36,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmDefaultSource",	0X38,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmPrintQuality",	0X3A,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmColor",	0X3C,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmDuplex",	0X3E,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmYResolution",	0X40,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmTTOption",	0X42,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmCollate",	0X44,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmFormName",	0X46,	0x000400,	-1,	32);
	AddStrucMember(id,"dmLogPixels",	0X66,	0x10000400,	-1,	2);
	AddStrucMember(id,"dmBitsPerPel",	0X68,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmPelsWidth",	0X6C,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmPelsHeight",	0X70,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmDisplayFlags",	0X74,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmDisplayFrequency",	0X78,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmICMMethod",	0X7C,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmICMIntent",	0X80,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmMediaType",	0X84,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmDitherType",	0X88,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmReserved1",	0X8C,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmReserved2",	0X90,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmPanningWidth",	0X94,	0x20000400,	-1,	4);
	AddStrucMember(id,"dmPanningHeight",	0X98,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("WSAData");
	AddStrucMember(id,"wVersion",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"wHighVersion",	0X2,	0x10000400,	-1,	2);
	AddStrucMember(id,"szDescription",	0X4,	0x000400,	-1,	257);
	AddStrucMember(id,"szSystemStatus",	0X105,	0x000400,	-1,	129);
	AddStrucMember(id,"iMaxSockets",	0X186,	0x10000400,	-1,	2);
	AddStrucMember(id,"iMaxUdpDg",	0X188,	0x10000400,	-1,	2);
	AddStrucMember(id,"lpVendorInfo",	0X18C,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("FILETIME");
	AddStrucMember(id,"dwLowDateTime",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwHighDateTime",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("_WIN32_FIND_DATAA");
	AddStrucMember(id,"dwFileAttributes",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"ftCreationTime",	0X4,	0x60000400,	GetStrucIdByName("FILETIME"),	8);
	AddStrucMember(id,"ftLastAccessTime",	0XC,	0x60000400,	GetStrucIdByName("FILETIME"),	8);
	AddStrucMember(id,"ftLastWriteTime",	0X14,	0x60000400,	GetStrucIdByName("FILETIME"),	8);
	AddStrucMember(id,"nFileSizeHigh",	0X1C,	0x20000400,	-1,	4);
	AddStrucMember(id,"nFileSizeLow",	0X20,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwReserved0",	0X24,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwReserved1",	0X28,	0x20000400,	-1,	4);
	AddStrucMember(id,"cFileName",	0X2C,	0x000400,	-1,	260);
	AddStrucMember(id,"cAlternateFileName",	0X130,	0x000400,	-1,	14);
	AddStrucMember(id,"_padding",	0X13E,	0x000400,	-1,	2);
	
	id = GetStrucIdByName("RECT");
	AddStrucMember(id,"left",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"top",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"right",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"bottom",	0XC,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("FILE");
	AddStrucMember(id,"_ptr",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"_cnt",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"_base",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"_flag",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"_file",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"_charbuf",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"_bufsiz",	0X18,	0x20000400,	-1,	4);
	AddStrucMember(id,"_tmpfname",	0X1C,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("tm");
	AddStrucMember(id,"tm_sec",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_min",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_hour",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_mday",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_mon",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_year",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_wday",	0X18,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_yday",	0X1C,	0x20000400,	-1,	4);
	AddStrucMember(id,"tm_isdst",	0X20,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("sockaddr");
	AddStrucMember(id,"sa_family",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"sa_data",	0X2,	0x000400,	-1,	14);
	
	id = GetStrucIdByName("timeval");
	AddStrucMember(id,"tv_sec",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"tv_usec",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("fd_set");
	AddStrucMember(id,"fd_count",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"fd_array",	0X4,	0x20000400,	-1,	256);
	
	id = GetStrucIdByName("WNDCLASSEXA");
	AddStrucMember(id,"cbSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"style",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpfnWndProc",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"cbClsExtra",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"cbWndExtra",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"hInstance",	0X14,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIcon",	0X18,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hCursor",	0X1C,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hbrBackground",	0X20,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszMenuName",	0X24,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszClassName",	0X28,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIconSm",	0X2C,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("tagWNDCLASSEXA");
	AddStrucMember(id,"cbSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"style",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpfnWndProc",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"cbClsExtra",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"cbWndExtra",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"hInstance",	0X14,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIcon",	0X18,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hCursor",	0X1C,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hbrBackground",	0X20,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszMenuName",	0X24,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszClassName",	0X28,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIconSm",	0X2C,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("RGBQUAD");
	AddStrucMember(id,"rgbBlue",	0X0,	0x000400,	-1,	1);
	AddStrucMember(id,"rgbGreen",	0X1,	0x000400,	-1,	1);
	AddStrucMember(id,"rgbRed",	0X2,	0x000400,	-1,	1);
	AddStrucMember(id,"rgbReserved",	0X3,	0x000400,	-1,	1);
	
	id = GetStrucIdByName("BITMAPINFOHEADER");
	AddStrucMember(id,"biSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"biWidth",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"biHeight",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"biPlanes",	0XC,	0x10000400,	-1,	2);
	AddStrucMember(id,"biBitCount",	0XE,	0x10000400,	-1,	2);
	AddStrucMember(id,"biCompression",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"biSizeImage",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"biXPelsPerMeter",	0X18,	0x20000400,	-1,	4);
	AddStrucMember(id,"biYPelsPerMeter",	0X1C,	0x20000400,	-1,	4);
	AddStrucMember(id,"biClrUsed",	0X20,	0x20000400,	-1,	4);
	AddStrucMember(id,"biClrImportant",	0X24,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("BITMAPINFO");
	AddStrucMember(id,"bmiHeader",	0X0,	0x60000400,	GetStrucIdByName("BITMAPINFOHEADER"),	40);
	AddStrucMember(id,"bmiColors",	0X28,	0x60000400,	GetStrucIdByName("RGBQUAD"),	4);
	
	id = GetStrucIdByName("tagINITCOMMONCONTROLSEX");
	AddStrucMember(id,"dwSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwICC",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("_OSVERSIONINFOA");
	AddStrucMember(id,"dwOSVersionInfoSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwMajorVersion",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwMinorVersion",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwBuildNumber",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwPlatformId",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"szCSDVersion",	0X14,	0x000400,	-1,	128);
	
	id = GetStrucIdByName("_SYSTEMTIME");
	AddStrucMember(id,"wYear",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMonth",	0X2,	0x10000400,	-1,	2);
	AddStrucMember(id,"wDayOfWeek",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"wDay",	0X6,	0x10000400,	-1,	2);
	AddStrucMember(id,"wHour",	0X8,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMinute",	0XA,	0x10000400,	-1,	2);
	AddStrucMember(id,"wSecond",	0XC,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMilliseconds",	0XE,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2::$AA04DEB0C6383F89F13D312A174572A9");
	AddStrucMember(id,"wProcessorArchitecture",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"wReserved",	0X2,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2");
	AddStrucMember(id,"dwOemId",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2::$AA04DEB0C6383F89F13D312A174572A9"),	4);
	
	id = GetStrucIdByName("_SYSTEM_INFO");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("_SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2"),	4);
	AddStrucMember(id,"dwPageSize",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpMinimumApplicationAddress",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpMaximumApplicationAddress",	0XC,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"dwActiveProcessorMask",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwNumberOfProcessors",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwProcessorType",	0X18,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwAllocationGranularity",	0X1C,	0x20000400,	-1,	4);
	AddStrucMember(id,"wProcessorLevel",	0X20,	0x10000400,	-1,	2);
	AddStrucMember(id,"wProcessorRevision",	0X22,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E");
	AddStrucMember(id,"LowPart",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"HighPart",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("LARGE_INTEGER");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E"),	8);
	AddStrucMember(id,"u",	0X0,	0x60000400,	GetStrucIdByName("_LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E"),	8);
	AddStrucMember(id,"QuadPart",	0X0,	0x30000400,	-1,	8);
	
	id = GetStrucIdByName("_SECURITY_ATTRIBUTES");
	AddStrucMember(id,"nLength",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpSecurityDescriptor",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"bInheritHandle",	0X8,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("SYSTEMTIME");
	AddStrucMember(id,"wYear",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMonth",	0X2,	0x10000400,	-1,	2);
	AddStrucMember(id,"wDayOfWeek",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"wDay",	0X6,	0x10000400,	-1,	2);
	AddStrucMember(id,"wHour",	0X8,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMinute",	0XA,	0x10000400,	-1,	2);
	AddStrucMember(id,"wSecond",	0XC,	0x10000400,	-1,	2);
	AddStrucMember(id,"wMilliseconds",	0XE,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("_TIME_ZONE_INFORMATION");
	AddStrucMember(id,"Bias",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"StandardName",	0X4,	0x10000400,	-1,	64);
	AddStrucMember(id,"StandardDate",	0X44,	0x60000400,	GetStrucIdByName("SYSTEMTIME"),	16);
	AddStrucMember(id,"StandardBias",	0X54,	0x20000400,	-1,	4);
	AddStrucMember(id,"DaylightName",	0X58,	0x10000400,	-1,	64);
	AddStrucMember(id,"DaylightDate",	0X98,	0x60000400,	GetStrucIdByName("SYSTEMTIME"),	16);
	AddStrucMember(id,"DaylightBias",	0XA8,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("_STARTUPINFOA");
	AddStrucMember(id,"cb",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpReserved",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpDesktop",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpTitle",	0XC,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"dwX",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwY",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwXSize",	0X18,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwYSize",	0X1C,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwXCountChars",	0X20,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwYCountChars",	0X24,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwFillAttribute",	0X28,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwFlags",	0X2C,	0x20000400,	-1,	4);
	AddStrucMember(id,"wShowWindow",	0X30,	0x10000400,	-1,	2);
	AddStrucMember(id,"cbReserved2",	0X32,	0x10000400,	-1,	2);
	AddStrucMember(id,"lpReserved2",	0X34,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hStdInput",	0X38,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hStdOutput",	0X3C,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hStdError",	0X40,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("_cpinfo");
	AddStrucMember(id,"MaxCharSize",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"DefaultChar",	0X4,	0x000400,	-1,	2);
	AddStrucMember(id,"LeadByte",	0X6,	0x000400,	-1,	12);
	AddStrucMember(id,"_padding",	0X12,	0x000400,	-1,	2);
	
	id = GetStrucIdByName("_FILETIME");
	AddStrucMember(id,"dwLowDateTime",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"dwHighDateTime",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("KDHELP");
	AddStrucMember(id,"Thread",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"ThCallbackStack",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"NextCallback",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"FramePointer",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"KiCallUserMode",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"KeUserCallbackDispatcher",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"SystemRangeStart",	0X18,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("ADDRESS");
	AddStrucMember(id,"Offset",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"Segment",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"Mode",	0X8,	0x28800400,	GetEnum("ADDRESS_MODE"),	4);
	
	id = GetStrucIdByName("_tagSTACKFRAME");
	AddStrucMember(id,"AddrPC",	0X0,	0x60000400,	GetStrucIdByName("ADDRESS"),	12);
	AddStrucMember(id,"AddrReturn",	0XC,	0x60000400,	GetStrucIdByName("ADDRESS"),	12);
	AddStrucMember(id,"AddrFrame",	0X18,	0x60000400,	GetStrucIdByName("ADDRESS"),	12);
	AddStrucMember(id,"AddrStack",	0X24,	0x60000400,	GetStrucIdByName("ADDRESS"),	12);
	AddStrucMember(id,"FuncTableEntry",	0X30,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"Params",	0X34,	0x20000400,	-1,	16);
	AddStrucMember(id,"Far",	0X44,	0x20000400,	-1,	4);
	AddStrucMember(id,"Virtual",	0X48,	0x20000400,	-1,	4);
	AddStrucMember(id,"Reserved",	0X4C,	0x20000400,	-1,	12);
	AddStrucMember(id,"KdHelp",	0X58,	0x60000400,	GetStrucIdByName("KDHELP"),	28);
	
	id = GetStrucIdByName("_MEMORY_BASIC_INFORMATION");
	AddStrucMember(id,"BaseAddress",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"AllocationBase",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"AllocationProtect",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"RegionSize",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"State",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"Protect",	0X14,	0x20000400,	-1,	4);
	AddStrucMember(id,"Type",	0X18,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("LOGFONTA");
	AddStrucMember(id,"lfHeight",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lfWidth",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"lfEscapement",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"lfOrientation",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"lfWeight",	0X10,	0x20000400,	-1,	4);
	AddStrucMember(id,"lfItalic",	0X14,	0x000400,	-1,	1);
	AddStrucMember(id,"lfUnderline",	0X15,	0x000400,	-1,	1);
	AddStrucMember(id,"lfStrikeOut",	0X16,	0x000400,	-1,	1);
	AddStrucMember(id,"lfCharSet",	0X17,	0x000400,	-1,	1);
	AddStrucMember(id,"lfOutPrecision",	0X18,	0x000400,	-1,	1);
	AddStrucMember(id,"lfClipPrecision",	0X19,	0x000400,	-1,	1);
	AddStrucMember(id,"lfQuality",	0X1A,	0x000400,	-1,	1);
	AddStrucMember(id,"lfPitchAndFamily",	0X1B,	0x000400,	-1,	1);
	AddStrucMember(id,"lfFaceName",	0X1C,	0x000400,	-1,	32);
	
	id = GetStrucIdByName("tagSIZE");
	AddStrucMember(id,"_cx",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"cy",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("tagRECT");
	AddStrucMember(id,"left",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"top",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"right",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"bottom",	0XC,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("ICONINFO");
	AddStrucMember(id,"fIcon",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"xHotspot",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"yHotspot",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"hbmMask",	0XC,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hbmColor",	0X10,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("WNDCLASSA");
	AddStrucMember(id,"style",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpfnWndProc",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"cbClsExtra",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"cbWndExtra",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"hInstance",	0X10,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIcon",	0X14,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hCursor",	0X18,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hbrBackground",	0X1C,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszMenuName",	0X20,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszClassName",	0X24,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("IID");
	AddStrucMember(id,"Data1",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"Data2",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"Data3",	0X6,	0x10000400,	-1,	2);
	AddStrucMember(id,"Data4",	0X8,	0x000400,	-1,	8);
	
	id = GetStrucIdByName("CLSID");
	AddStrucMember(id,"Data1",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"Data2",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"Data3",	0X6,	0x10000400,	-1,	2);
	AddStrucMember(id,"Data4",	0X8,	0x000400,	-1,	8);
	
	id = GetStrucIdByName("tagWNDCLASSA");
	AddStrucMember(id,"style",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lpfnWndProc",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"cbClsExtra",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"cbWndExtra",	0XC,	0x20000400,	-1,	4);
	AddStrucMember(id,"hInstance",	0X10,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hIcon",	0X14,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hCursor",	0X18,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"hbrBackground",	0X1C,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszMenuName",	0X20,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"lpszClassName",	0X24,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("SAFEARRAYBOUND");
	AddStrucMember(id,"cElements",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"lLbound",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301::$674876891A86A76F12C10005982BCA56");
	AddStrucMember(id,"Lo32",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"Mid32",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301::$674876891A86A76F12C10005982BCA56"),	8);
	AddStrucMember(id,"Lo64",	0X0,	0x30000400,	-1,	8);
	
	id = GetStrucIdByName("tagDEC::$64EC678C49E7BE49873AFBFB7A849D34::$7F8459940C2B08BD5D82B0F27239141B");
	AddStrucMember(id,"scale",	0X0,	0x000400,	-1,	1);
	AddStrucMember(id,"sign",	0X1,	0x000400,	-1,	1);
	
	id = GetStrucIdByName("tagDEC::$64EC678C49E7BE49873AFBFB7A849D34");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagDEC::$64EC678C49E7BE49873AFBFB7A849D34::$7F8459940C2B08BD5D82B0F27239141B"),	2);
	AddStrucMember(id,"signscale",	0X0,	0x10000400,	-1,	2);
	
	id = GetStrucIdByName("DECIMAL");
	AddStrucMember(id,"wReserved",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"anonymous_0",	0X2,	0x60000400,	GetStrucIdByName("tagDEC::$64EC678C49E7BE49873AFBFB7A849D34"),	2);
	AddStrucMember(id,"Hi32",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"anonymous_1",	0X8,	0x60000400,	GetStrucIdByName("tagDEC::$D28E26DEC3EC762C06C2AA9D0F7AC301"),	8);
	
	id = GetStrucIdByName("tagVARIANT::$::$::$0BEA0A4089964397D04279FA271AA80F::$0FDBD249F1AECD6A49409B6B82281578");
	AddStrucMember(id,"pvRecord",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pRecInfo",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	
	id = GetStrucIdByName("tagCY::$4ADA6AE34E722E24764E0C4FBCDA3E73");
	AddStrucMember(id,"Lo",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"Hi",	0X4,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("CY");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagCY::$4ADA6AE34E722E24764E0C4FBCDA3E73"),	8);
	AddStrucMember(id,"int64",	0X0,	0x30000400,	-1,	8);
	
	id = GetStrucIdByName("tagVARIANT::$::$96DBE208241BA05363E12043D50C05A8::$0BEA0A4089964397D04279FA271AA80F");
	AddStrucMember(id,"lVal",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"bVal",	0X0,	0x000400,	-1,	1);
	AddStrucMember(id,"iVal",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"fltVal",	0X0,	0x80000400,	-1,	4);
	AddStrucMember(id,"dblVal",	0X0,	0x90000400,	-1,	8);
	AddStrucMember(id,"boolVal",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"scode",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"cyVal",	0X0,	0x60000400,	GetStrucIdByName("CY"),	8);
	AddStrucMember(id,"date",	0X0,	0x90000400,	-1,	8);
	AddStrucMember(id,"bstrVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"punkVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pdispVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"parray",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pbVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"piVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"plVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pfltVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pdblVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pboolVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pscode",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pcyVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pdate",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pbstrVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"ppunkVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"ppdispVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pparray",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pvarVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"byref",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"cVal",	0X0,	0x000400,	-1,	1);
	AddStrucMember(id,"uiVal",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"ulVal",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"intVal",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"uintVal",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"pdecVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pcVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"puiVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pulVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"pintVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"puintVal",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagVARIANT::$::$::$0BEA0A4089964397D04279FA271AA80F::$0FDBD249F1AECD6A49409B6B82281578"),	8);
	
	id = GetStrucIdByName("tagVARIANT::$33EB7139E59CDB065A159F13B94F651E::$96DBE208241BA05363E12043D50C05A8");
	AddStrucMember(id,"vt",	0X0,	0x10000400,	-1,	2);
	AddStrucMember(id,"wReserved1",	0X2,	0x10000400,	-1,	2);
	AddStrucMember(id,"wReserved2",	0X4,	0x10000400,	-1,	2);
	AddStrucMember(id,"wReserved3",	0X6,	0x10000400,	-1,	2);
	AddStrucMember(id,"anonymous_0",	0X8,	0x60000400,	GetStrucIdByName("tagVARIANT::$::$96DBE208241BA05363E12043D50C05A8::$0BEA0A4089964397D04279FA271AA80F"),	8);
	
	id = GetStrucIdByName("tagVARIANT::$33EB7139E59CDB065A159F13B94F651E");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagVARIANT::$33EB7139E59CDB065A159F13B94F651E::$96DBE208241BA05363E12043D50C05A8"),	16);
	AddStrucMember(id,"decVal",	0X0,	0x60000400,	GetStrucIdByName("DECIMAL"),	16);
	
	id = GetStrucIdByName("VARIANTARG");
	AddStrucMember(id,"anonymous_0",	0X0,	0x60000400,	GetStrucIdByName("tagVARIANT::$33EB7139E59CDB065A159F13B94F651E"),	16);
	
	id = GetStrucIdByName("_RTL_CRITICAL_SECTION");
	AddStrucMember(id,"DebugInfo",	0X0,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"LockCount",	0X4,	0x20000400,	-1,	4);
	AddStrucMember(id,"RecursionCount",	0X8,	0x20000400,	-1,	4);
	AddStrucMember(id,"OwningThread",	0XC,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"LockSemaphore",	0X10,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"SpinCount",	0X14,	0x20000400,	-1,	4);
	
	id = GetStrucIdByName("CPPEH_RECORD");
	AddStrucMember(id,"old_esp",	0X0,	0x20000400,	-1,	4);
	AddStrucMember(id,"exc_ptr",	0X4,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"prev_er",	0X8,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"handler",	0XC,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"msEH_ptr",	0X10,	0x25500400,	0XFFFFFFFF,	4);
	AddStrucMember(id,"disabled",	0X14,	0x20000400,	-1,	4);
	return id;
}

//------------------------------------------------------------------------
// Information about structure types

static Structures(void) {
        auto id;
	id = Structures_0(id);
}

// End of file.
