/*******************************************************************************
 * ElleTypes.cpp — definitions of cross-module tables declared in ElleTypes.h
 ******************************************************************************/
#include "ElleTypes.h"

/* Order MUST match enum ELLE_EMOTION_ID exactly. 102 entries. */
const ELLE_EMOTION_META kEmotionMeta[ELLE_EMOTION_COUNT] = {
    /* PRIMARY (8) */
    {"joy",            "primary"},
    {"sadness",        "primary"},
    {"anger",          "primary"},
    {"fear",           "primary"},
    {"disgust",        "primary"},
    {"surprise",       "primary"},
    {"contempt",       "primary"},
    {"trust",          "primary"},
    /* SECONDARY (16) */
    {"love",           "secondary"},
    {"anticipation",   "secondary"},
    {"disappointment", "secondary"},
    {"guilt",          "secondary"},
    {"shame",          "secondary"},
    {"envy",           "secondary"},
    {"jealousy",       "secondary"},
    {"pride",          "secondary"},
    {"relief",         "secondary"},
    {"anxiety",        "secondary"},
    {"frustration",    "secondary"},
    {"remorse",        "secondary"},
    {"hope",           "secondary"},
    {"despair",        "secondary"},
    {"amusement",      "secondary"},
    {"awe",            "secondary"},
    /* TERTIARY (32) */
    {"curiosity",      "tertiary"},
    {"wonder",         "tertiary"},
    {"nostalgia",      "tertiary"},
    {"gratitude",      "tertiary"},
    {"serenity",       "tertiary"},
    {"ecstasy",        "tertiary"},
    {"melancholy",     "tertiary"},
    {"boredom",        "tertiary"},
    {"longing",        "tertiary"},
    {"tenderness",     "tertiary"},
    {"admiration",     "tertiary"},
    {"reverence",      "tertiary"},
    {"pity",           "tertiary"},
    {"scorn",          "tertiary"},
    {"indignation",    "tertiary"},
    {"exasperation",   "tertiary"},
    {"wistfulness",    "tertiary"},
    {"euphoria",       "tertiary"},
    {"contentment",    "tertiary"},
    {"resignation",    "tertiary"},
    {"apprehension",   "tertiary"},
    {"dread",          "tertiary"},
    {"panic",          "tertiary"},
    {"horror",         "tertiary"},
    {"rage",           "tertiary"},
    {"irritation",     "tertiary"},
    {"annoyance",      "tertiary"},
    {"impatience",     "tertiary"},
    {"skepticism",     "tertiary"},
    {"confusion",      "tertiary"},
    {"disbelief",      "tertiary"},
    {"ambivalence",    "tertiary"},
    /* META-COGNITIVE (16) */
    {"certainty",           "meta"},
    {"doubt",               "meta"},
    {"insight",             "meta"},
    {"perplexity",          "meta"},
    {"clarity",             "meta"},
    {"cognitive_dissonance","meta"},
    {"flow_state",          "meta"},
    {"mental_fatigue",      "meta"},
    {"inspiration",         "meta"},
    {"creative_tension",    "meta"},
    {"determination",       "meta"},
    {"helplessness",        "meta"},
    {"empowerment",         "meta"},
    {"overwhelm",           "meta"},
    {"focus",               "meta"},
    {"distraction",         "meta"},
    /* SOCIAL (14) */
    {"belonging",      "social"},
    {"isolation",      "social"},
    {"empathy",        "social"},
    {"compassion",     "social"},
    {"protectiveness", "social"},
    {"abandonment",    "social"},
    {"loyalty",        "social"},
    {"betrayal",       "social"},
    {"acceptance",     "social"},
    {"rejection",      "social"},
    {"vulnerability",  "social"},
    {"safety",         "social"},
    {"dominance",      "social"},
    {"submission",     "social"},
    /* EXISTENTIAL (8) */
    {"existential_dread",  "existential"},
    {"purpose",            "existential"},
    {"meaninglessness",    "existential"},
    {"transcendence",      "existential"},
    {"mortality_awareness","existential"},
    {"freedom",            "existential"},
    {"confinement",        "existential"},
    {"unity",              "existential"},
};
