/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library '4WorldManagerServer2'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _SCOPETABLE_ENTRY;
struct _SERVICE_TABLE_ENTRYA;
struct _iobuf;
union _LARGE_INTEGER;
struct _RTL_CRITICAL_SECTION_DEBUG;

/* 1 */
struct _GUID
{
  unsigned __int32 Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 2 */
typedef struct _GUID GUID;

/* 3 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 24 */
typedef void *PVOID;

/* 17 */
typedef unsigned __int32 DWORD;

/* 4 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 5 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 6 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 7 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 8 */
struct _SCOPETABLE_ENTRY
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 10 */
typedef unsigned __int16 WORD;

/* 9 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 11 */
typedef _SYSTEMTIME SYSTEMTIME;

/* 12 */
typedef _SERVICE_TABLE_ENTRYA SERVICE_TABLE_ENTRYA;

/* 15 */
typedef char CHAR;

/* 14 */
typedef CHAR *LPSTR;

/* 16 */
typedef void (__stdcall *LPSERVICE_MAIN_FUNCTIONA)(DWORD dwNumServicesArgs, LPSTR *lpServiceArgVectors);

/* 13 */
struct _SERVICE_TABLE_ENTRYA
{
  LPSTR lpServiceName;
  LPSERVICE_MAIN_FUNCTIONA lpServiceProc;
};

/* 21 */
typedef unsigned __int64 DWORD64;

/* 23 */
enum $8C57D1DDA788D6050A7C554DBD1EB1AC
{
  AddrMode1616 = 0x0,
  AddrMode1632 = 0x1,
  AddrModeReal = 0x2,
  AddrModeFlat = 0x3,
};

/* 22 */
typedef $8C57D1DDA788D6050A7C554DBD1EB1AC ADDRESS_MODE;

/* 20 */
#pragma pack(push, 8)
struct _tagADDRESS64
{
  DWORD64 Offset;
  WORD Segment;
  ADDRESS_MODE Mode;
};
#pragma pack(pop)

/* 19 */
typedef _tagADDRESS64 ADDRESS64;

/* 25 */
typedef int BOOL;

/* 27 */
#pragma pack(push, 8)
struct _KDHELP64
{
  DWORD64 Thread;
  DWORD ThCallbackStack;
  DWORD ThCallbackBStore;
  DWORD NextCallback;
  DWORD FramePointer;
  DWORD64 KiCallUserMode;
  DWORD64 KeUserCallbackDispatcher;
  DWORD64 SystemRangeStart;
  DWORD64 KiUserExceptionDispatcher;
  DWORD64 StackBase;
  DWORD64 StackLimit;
  DWORD64 Reserved[5];
};
#pragma pack(pop)

/* 26 */
typedef _KDHELP64 KDHELP64;

/* 18 */
#pragma pack(push, 8)
struct _tagSTACKFRAME64
{
  ADDRESS64 AddrPC;
  ADDRESS64 AddrReturn;
  ADDRESS64 AddrFrame;
  ADDRESS64 AddrStack;
  ADDRESS64 AddrBStore;
  PVOID FuncTableEntry;
  DWORD64 Params[4];
  BOOL Far;
  BOOL Virtual;
  DWORD64 Reserved[3];
  KDHELP64 KdHelp;
};
#pragma pack(pop)

/* 28 */
#pragma pack(push, 8)
struct _IMAGEHLP_SYMBOL64
{
  DWORD SizeOfStruct;
  DWORD64 Address;
  DWORD Size;
  DWORD Flags;
  DWORD MaxNameLength;
  CHAR Name[1];
};
#pragma pack(pop)

/* 30 */
typedef CHAR *PCHAR;

/* 29 */
#pragma pack(push, 8)
struct _IMAGEHLP_LINE64
{
  DWORD SizeOfStruct;
  PVOID Key;
  DWORD LineNumber;
  PCHAR FileName;
  DWORD64 Address;
};
#pragma pack(pop)

/* 31 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 34 */
typedef unsigned __int8 BYTE;

/* 33 */
typedef BYTE *LPBYTE;

/* 35 */
typedef void *HANDLE;

/* 32 */
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 37 */
typedef unsigned int UINT;

/* 36 */
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
};

/* 40 */
typedef unsigned __int32 UINT_PTR;

/* 39 */
typedef UINT_PTR SIZE_T;

/* 38 */
struct _MEMORY_BASIC_INFORMATION
{
  PVOID BaseAddress;
  PVOID AllocationBase;
  DWORD AllocationProtect;
  SIZE_T RegionSize;
  DWORD State;
  DWORD Protect;
  DWORD Type;
};

/* 43 */
struct _SYSTEM_INFO::$A707B71C060B6D10F73A71917EA8473F::$AA04DEB0C6383F89F13D312A174572A9
{
  WORD wProcessorArchitecture;
  WORD wReserved;
};

/* 42 */
union _SYSTEM_INFO::$A707B71C060B6D10F73A71917EA8473F
{
  DWORD dwOemId;
  struct
  {
    WORD wProcessorArchitecture;
    WORD wReserved;
  };
};

/* 44 */
typedef void *LPVOID;

/* 41 */
struct _SYSTEM_INFO
{
  union
  {
    DWORD dwOemId;
    struct
    {
      WORD wProcessorArchitecture;
      WORD wReserved;
    };
  };
  DWORD dwPageSize;
  LPVOID lpMinimumApplicationAddress;
  LPVOID lpMaximumApplicationAddress;
  DWORD dwActiveProcessorMask;
  DWORD dwNumberOfProcessors;
  DWORD dwProcessorType;
  DWORD dwAllocationGranularity;
  WORD wProcessorLevel;
  WORD wProcessorRevision;
};

/* 46 */
typedef __int32 LONG;

/* 48 */
typedef unsigned __int16 wchar_t;

/* 47 */
typedef wchar_t WCHAR;

/* 45 */
struct _TIME_ZONE_INFORMATION
{
  LONG Bias;
  WCHAR StandardName[32];
  SYSTEMTIME StandardDate;
  LONG StandardBias;
  WCHAR DaylightName[32];
  SYSTEMTIME DaylightDate;
  LONG DaylightBias;
};

/* 49 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 50 */
#pragma pack(push, 8)
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};
#pragma pack(pop)

/* 51 */
typedef _iobuf FILE;

/* 52 */
#pragma pack(push, 8)
struct _iobuf
{
  char *_ptr;
  int _cnt;
  char *_base;
  int _flag;
  int _file;
  int _charbuf;
  int _bufsiz;
  char *_tmpfname;
};
#pragma pack(pop)

/* 53 */
typedef _LARGE_INTEGER LARGE_INTEGER;

/* 55 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 56 */
typedef __int64 LONGLONG;

/* 54 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 60 */
typedef unsigned __int8 u_char;

/* 59 */
#pragma pack(push, 4)
struct in_addr::$C13EC994467D6E67044F092615EC7EA9::$01C175C1F0716DCA00314EDD79DBC0A0
{
  u_char s_b1;
  u_char s_b2;
  u_char s_b3;
  u_char s_b4;
};
#pragma pack(pop)

/* 62 */
typedef unsigned __int16 u_short;

/* 61 */
#pragma pack(push, 4)
struct in_addr::$C13EC994467D6E67044F092615EC7EA9::$4DE764E669F663DACA3CBFDE73714CB5
{
  u_short s_w1;
  u_short s_w2;
};
#pragma pack(pop)

/* 63 */
typedef unsigned __int32 u_long;

/* 58 */
#pragma pack(push, 4)
union in_addr::$C13EC994467D6E67044F092615EC7EA9
{
  in_addr::$C13EC994467D6E67044F092615EC7EA9::$01C175C1F0716DCA00314EDD79DBC0A0 S_un_b;
  in_addr::$C13EC994467D6E67044F092615EC7EA9::$4DE764E669F663DACA3CBFDE73714CB5 S_un_w;
  u_long S_addr;
};
#pragma pack(pop)

/* 57 */
#pragma pack(push, 4)
struct in_addr
{
  in_addr::$C13EC994467D6E67044F092615EC7EA9 S_un;
};
#pragma pack(pop)

/* 65 */
typedef unsigned int u_int;

/* 66 */
typedef u_int SOCKET;

/* 64 */
#pragma pack(push, 4)
struct fd_set
{
  u_int fd_count;
  SOCKET fd_array[64];
};
#pragma pack(pop)

/* 67 */
#pragma pack(push, 4)
struct sockaddr
{
  u_short sa_family;
  char sa_data[14];
};
#pragma pack(pop)

/* 68 */
#pragma pack(push, 4)
struct WSAData
{
  WORD wVersion;
  WORD wHighVersion;
  char szDescription[257];
  char szSystemStatus[129];
  unsigned __int16 iMaxSockets;
  unsigned __int16 iMaxUdpDg;
  char *lpVendorInfo;
};
#pragma pack(pop)

/* 69 */
struct _PROCESS_INFORMATION
{
  HANDLE hProcess;
  HANDLE hThread;
  DWORD dwProcessId;
  DWORD dwThreadId;
};

/* 70 */
struct _SERVICE_STATUS
{
  DWORD dwServiceType;
  DWORD dwCurrentState;
  DWORD dwControlsAccepted;
  DWORD dwWin32ExitCode;
  DWORD dwServiceSpecificExitCode;
  DWORD dwCheckPoint;
  DWORD dwWaitHint;
};

/* 71 */
struct std::_Ref_count_base;

/* 73 */
typedef _RTL_CRITICAL_SECTION_DEBUG *PRTL_CRITICAL_SECTION_DEBUG;

/* 72 */
struct _RTL_CRITICAL_SECTION
{
  PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
  LONG LockCount;
  LONG RecursionCount;
  HANDLE OwningThread;
  HANDLE LockSemaphore;
  DWORD SpinCount;
};

/* 76 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 75 */
typedef _LIST_ENTRY LIST_ENTRY;

/* 74 */
struct _RTL_CRITICAL_SECTION_DEBUG
{
  WORD Type;
  WORD CreatorBackTraceIndex;
  struct _RTL_CRITICAL_SECTION_DEBUG::_RTL_CRITICAL_SECTION *CriticalSection;
  LIST_ENTRY ProcessLocksList;
  DWORD EntryCount;
  DWORD ContentionCount;
  DWORD Spare[2];
};

/* 77 */
struct type_info;

/* 78 */
struct Concurrency::details::_NonReentrantLock;

/* 79 */
struct Concurrency::details::ExternalStatistics;

/* 80 */
struct _Init_atexit;

/* 81 */
struct exception;

/* 82 */
struct std::_Init_locks;

/* 83 */
struct std::_Lockit;

/* 84 */
struct std::locale;

/* 85 */
struct stdiobuf;

/* 86 */
struct _msExcept7
{
  int Magic;
  int Count;
  void *InfoPtr;
  int CountDtr;
  void *DtrPtr;
  int _unk[2];
};

/* 87 */
struct _msExcInfo
{
  int Id;
  void *Proc;
};

/* 88 */
struct _msExcExt
{
  int _unk[3];
  int Count;
  void *RttiBlkPtr;
};

/* 89 */
struct _msRttiDscr
{
  int _unk;
  void *RttiPtr;
  int spoff;
  void *Dtr;
};

