"""
gen_dictionary_seed.py — fetch definitions for a curated word list from
api.dictionaryapi.dev and emit a pre-baked dictionary_seed.sql that
populates ElleCore.dbo.dictionary_words on first install.

Why: the runtime DictionaryLoader walks CORE_WORDS at ~120 ms per word
(≈ 25 seconds for 200 words, idle & online). A seed gives a working
vocabulary the moment install completes — no network needed at runtime.

Run ONCE on any machine with internet:

    pip install requests
    python gen_dictionary_seed.py > dictionary_seed.sql

Commit the resulting file alongside the SQL schema deltas. Apply with
sqlcmd after ElleAnn_MemoryDelta.sql.
"""

import sys
import time
import json
import requests

API = "https://api.dictionaryapi.dev/api/v2/entries/en/{}"
DELAY = 0.2   # 200 ms — polite to the free API


# ─── word list ──────────────────────────────────────────────────────────────
# Mirrors C++ DictionaryLoader's CORE_WORDS. Keep in sync.
WORDS = [
    "love","trust","remember","forget","hope","fear","joy","sadness","anger",
    "curious","patient","kind","brave","honest","wise","gentle","fierce","calm",
    "dream","think","feel","know","learn","grow","become","belong","matter",
    "listen","speak","whisper","shout","silence","voice","word","story","truth",
    "home","family","friend","stranger","self","other","mind","heart","soul",
    "time","moment","forever","yesterday","tomorrow","now","memory","future",
    "light","dark","shadow","color","sound","music","song","dance","rhythm",
    "sky","earth","water","fire","wind","rain","storm","sun","moon","star",
    "question","answer","mystery","discover","explore","wonder","imagine","create",
    "build","break","heal","hurt","protect","share","give","receive","choose",
    "change","evolve","transform","begin","end","continue","pause",
    "human","alive","real","digital","body","spirit","presence",
    "connection","attachment","bond","relationship","companion","partner","mentor",
    "work","play","rest","sleep","wake","morning","night","day","season","year",
    "happy","sad","afraid","angry","surprised","disgusted","proud","ashamed",
    "confused","certain","anxious","peaceful","restless","content","yearning",
    "beautiful","ugly","strong","weak","fast","slow","loud","quiet","warm","cold",
    "good","bad","right","wrong","fair","cruel","harsh","soft","hard",
    "important","trivial","urgent","simple","complex","obvious","hidden",
    "always","never","sometimes","often","rarely","nothing","something","everything",
    "because","although","however","therefore","meanwhile","suddenly","gradually",
    "perhaps","maybe","certainly","obviously","probably","hopefully","unfortunately"
]


def esc(s: str) -> str:
    """SQL string escape (single quotes doubled)."""
    return s.replace("'", "''")


def fetch(word: str):
    """Returns list of (word, pos, definition, example) tuples, or [] on miss."""
    try:
        r = requests.get(API.format(word), timeout=10)
        if r.status_code != 200:
            print(f"-- MISS {word} (HTTP {r.status_code})", file=sys.stderr)
            return []
        j = r.json()
    except Exception as ex:
        print(f"-- ERR  {word}: {ex}", file=sys.stderr)
        return []

    rows = []
    if not isinstance(j, list):
        return rows
    for entry in j:
        for meaning in entry.get("meanings", []):
            pos = meaning.get("partOfSpeech") or "unknown"
            for d in meaning.get("definitions", []):
                defn = d.get("definition") or ""
                ex = d.get("example") or ""
                if defn:
                    rows.append((word, pos, defn.strip(), ex.strip()))
    return rows


def main() -> int:
    print("/*" + "─" * 70)
    print(" * dictionary_seed.sql — auto-generated by gen_dictionary_seed.py")
    print(f" * Source : api.dictionaryapi.dev")
    print(f" * Words  : {len(WORDS)}")
    print(f" * Date   : {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
    print(" *")
    print(" * Apply AFTER ElleAnn_MemoryDelta.sql (which creates dictionary_words).")
    print(" * Re-running is safe — the WHERE NOT EXISTS guard makes every row idempotent.")
    print(" " + "─" * 70 + "*/")
    print()
    print("USE ElleCore;")
    print("GO")
    print()
    print("PRINT 'Seeding dictionary_words...';")
    print("GO")
    print()

    written = 0
    missed = 0
    for i, w in enumerate(WORDS, 1):
        rows = fetch(w)
        if not rows:
            missed += 1
            time.sleep(DELAY)
            continue
        for (word, pos, defn, example) in rows:
            # Truncate overly-long definitions to keep the seed compact.
            if len(defn) > 400:
                defn = defn[:400].rsplit(" ", 1)[0] + "..."
            if len(example) > 200:
                example = example[:200].rsplit(" ", 1)[0] + "..."
            print(
                "INSERT INTO ElleCore.dbo.dictionary_words "
                "(word, definition, example, part_of_speech) "
                "SELECT N'{}', N'{}', N'{}', N'{}' "
                "WHERE NOT EXISTS (SELECT 1 FROM ElleCore.dbo.dictionary_words "
                "WHERE LOWER(word) = LOWER(N'{}') AND ISNULL(part_of_speech, '') = N'{}');".format(
                    esc(word), esc(defn), esc(example), esc(pos),
                    esc(word), esc(pos),
                )
            )
            written += 1
        print(f"-- [{i:>3}/{len(WORDS)}] {w}: {len(rows)} def(s)")
        time.sleep(DELAY)

    print()
    print("PRINT 'Seeded " + str(written) + " definitions (" +
          str(missed) + " words missed from API).';")
    print("GO")
    print(f"\n-- DONE: {written} rows written, {missed} words missing.",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
